name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Generate per-class schemas
        run: npm run gen:schemas

      - name: Validate schemas (Ajv)
        run: npm run validate:ajv

      - name: Bundle monolith
        run: npm run bundle:monolith

      - name: Lint $id/$ref URLs are canonical
        shell: bash
        run: |
          set -euo pipefail
          bad=$(git grep -nE '"(\$ref|\$id)"\s*:\s*"https?://[^"]*/(schema|schemas|mvp)/' -- packages || true)
          bad2=$(git grep -nE '"(\$ref|\$id)"\s*:\s*"https?://[^"]+\.json"' -- packages | grep -vE '\.schema\.json"' || true)
          if [[ -n "$bad$bad2" ]]; then
            echo "❌ Found non-canonical $ref/$id URLs:"
            echo "$bad"
            echo "$bad2"
            exit 1
          fi
